Models/ErrorViewModel.cs
using System;

namespace SS13Stats.Frontend.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ServerListModel.cs
using SS13Stats.Frontend.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SS13Stats.Frontend.Models {
    public class ServerListModel {
        // Yes I know this is technically a list of snapshots, but this is easier. Trust me.
        public List<Snapshot> servers { get; set; } = new List<Snapshot>();
    }
}

Models/ServerViewModel.cs
using SS13Stats.Frontend.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SS13Stats.Frontend.Models {
    public class ServerViewModel {
        public Server server { get; set; }
        public string day_snapshots_json { get; set; }
        public string week_snapshots_json { get; set; }
    }
}

Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using SS13Stats.Frontend.Database;
using SS13Stats.Frontend.Helpers;
using SS13Stats.Frontend.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace SS13Stats.Frontend.Controllers {
    [Route("")]
    public class BaseController : Controller {
        private readonly ILogger<BaseController> _logger;
        private readonly SS13StatsDBContext _dbc;

        public BaseController(ILogger<BaseController> logger, SS13StatsDBContext dbc) {
            _logger = logger;
            _dbc = dbc;
        }

        [Route("")]
        public IActionResult Index() {
            ServerListModel slm = new ServerListModel();
            List<Server> servers = _dbc.Servers.Where(s => s.LastSeen > DateTime.Now.AddDays(-1)).ToList();
            // Now we do ordering stuff
            List<Snapshot> latest_snaps = new List<Snapshot>();
            foreach(Server S in servers) {
                latest_snaps.Add(_dbc.Snapshots.Where(s => s.Server == S).OrderByDescending(s => s.SnapshotTime).First());
            }
            latest_snaps = latest_snaps.OrderByDescending(s => s.PlayerCount).ToList();
            slm.servers = latest_snaps;
            return View("Index", slm);
        }

        [Route("server/{serverid?}")]
        public IActionResult GetServer(int? serverid) {
            if(serverid == null) {
                return BadRequest("Please supply a server ID");
            }
            ServerViewModel svm = new ServerViewModel();
            if(_dbc.Servers.Where(s => s.Id == serverid).Any()) {
                svm.server = _dbc.Servers.Where(s => s.Id == serverid).First();
            } else {
                return NotFound("A server with ID " + serverid + " could not be found");
            }

            JsonSerializerSettings settings = new JsonSerializerSettings();
            settings.ContractResolver = new DictionaryAsArrayResolver();

            Dictionary<DateTime, int> snaps_24h = _dbc.Snapshots.Where(s => s.Server == svm.server).Where(s => s.SnapshotTime > DateTime.Now.AddDays(-1)).OrderBy(s => s.SnapshotTime).ToDictionary(s => s.SnapshotTime, s => s.PlayerCount);
            
            svm.day_snapshots_json = JsonConvert.SerializeObject(snaps_24h, settings);

            Dictionary<DateTime, int> snaps_7d = _dbc.Snapshots.Where(s => s.Server == svm.server).Where(s => s.SnapshotTime > DateTime.Now.AddDays(-7)).OrderBy(s => s.SnapshotTime).ToDictionary(s => s.SnapshotTime, s => s.PlayerCount);
            svm.week_snapshots_json = JsonConvert.SerializeObject(snaps_7d, settings);

            return View("ServerView", svm);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("error")]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Base/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
@model SS13Stats.Frontend.Models.ServerListModel;
@using SS13Stats.Frontend.Database; 

<h1 class="display-4 text-light">Server List</h1>
<p class="text-light"><i>Servers with &lt;5 players will not have their samples stored. This may cause gaps/inconsistencies in the graphs.</i></p>
<table class="table table-striped table-dark table-hover">
    <thead>
        <tr>
            <th scope="col" width="80%">
                Server Name
            </th>
            <th scope="col" width="20%">
                Current Playercount
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(Snapshot S in Model.servers) {
        <tr>
            <th scope="row" width="80%" class="text-break"><a class="text-white" asp-area="" asp-controller="Base" asp-action="GetServer" asp-route-serverid="@S.Server.Id"><u>@S.Server.ServerName</u></a></th>
            <td width="20%">@S.PlayerCount</td>
        </tr>
        }
    </tbody>
</table>

Views/Base/ServerView.cshtml
@using SS13Stats.Frontend.Models;
@model SS13Stats.Frontend.Models.ServerViewModel;
@{
    ViewData["Title"] = @Model.server.ServerName;
}
<h4><code>#@Model.server.Id</code></h4>
<h2 class="text-white" style="font-weight: 300">@Model.server.ServerName</h2>

<hr class="bg-white" />
<h4 class="text-white">Past 24 hours</h4>
<div style="width: 100%;" id="24h_chart"></div>

<hr class="bg-white" />
<h4 class="text-white">Past week</h4>
<div style="width: 100%;" id="7d_chart"></div>

<hr class="bg-white" />
<h4 class="text-white">Daily averages</h4>
<code>TODO</code>

<span style="display: none" id="24h_json">@Model.day_snapshots_json</span>
<span style="display: none" id="7d_json">@Model.week_snapshots_json</span>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
    // Load the Visualization API and the corechart package.
    google.charts.load('current', { 'packages': ['corechart'] });

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {
        // Define some stuff
        var chartTextStyle = { color: '#FFF' };
        var options = { title: "", legend: 'none', colors: ['#4287f5'], backgroundColor: { fill: 'transparent' }, titleTextStyle: { color: '#FFFFFF' }, height: "400", hAxis: { textStyle: chartTextStyle, titleTextStyle: chartTextStyle }, vAxis: { textStyle: chartTextStyle, titleTextStyle: chartTextStyle, gridlines: { color: '#787878' }, minValue: 0 }, chartArea: { 'width': '90%', 'height': '90%' }, };


        // Get the 24h history
        var raw_json_24h = JSON.parse(document.getElementById("24h_json").innerHTML);
        // Time to rip it apart and do shit
        let my_data_24h = [];
        my_data_24h.push(["Timestamp", "Players"]);
        raw_json_24h.forEach(e => {
            my_data_24h.push([e["Key"], e["Value"]]);
        })

        var data_24h = google.visualization.arrayToDataTable(my_data_24h);

        // Get the 7d history
        var raw_json_7d = JSON.parse(document.getElementById("7d_json").innerHTML);
        // Time to rip it apart and do shit
        let my_data_7d = [];
        my_data_7d.push(["Timestamp", "Players"]);
        raw_json_7d.forEach(e => {
            my_data_7d.push([e["Key"], e["Value"]]);
        })

        var data_7d = google.visualization.arrayToDataTable(my_data_7d);
        


        var chart_24h = new google.visualization.LineChart(document.getElementById('24h_chart'));
        var chart_7d = new google.visualization.LineChart(document.getElementById('7d_chart'));

        chart_24h.draw(data_24h, options);
        chart_7d.draw(data_7d, options);
    }
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SS13 Stats</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: #272727">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark mb-2">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SS13 Stats</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Base" asp-action="Index">Server List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Base" asp-action="Aggregate">Aggregated Stats</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="API" asp-action="Index">API</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-dark text-light">
        <div class="container">
            &copy; AffectedArc07 2021 - Inspired by <a class="text-primary" href="https://github.com/lmas/ss13.se">ss13.se</a> - <a class="text-primary" href="https://github.com/AffectedArc07/SS13Stats.Frontend">Source</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>